exam/urls.py
from django.urls import path
from exam.views import (
    index_view,
    exam_overview_view,
    exam_join_view,
    exam_view,
    check_answer_view,
    exam_results
)

app_name = "exam"

urlpatterns = [
    path("", index_view, name="index"),
    path("exams/<uuid:exam_id>/", exam_overview_view, name="exam_overview"),
    path("exams/<uuid:exam_id>/join/", exam_join_view, name="exam_join"),
    path("exam/<uuid:exam_id>/", exam_view, name="exam_view"),
    path(
        "exam/<uuid:exam_id>/<uuid:attempt_id>/", check_answer_view, name="check_answer"
    ),
    path("exam/<uuid:exam_id>/<uuid:attempt_id>/results/", exam_results, name="results")
]

quizzyy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("exam.urls", namespace="exam")),
    path("dashboard/", include("main.urls", namespace="main")),
    path("__debug__", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth import get_user_model
import uuid


# Create your models here.


class TimestampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class UUIDMixin(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)

    class Meta:
        abstract = True


class QuestionGroup(models.Model):
    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name


class Question(UUIDMixin):
    question = models.CharField(max_length=500)
    options = models.ManyToManyField("Option", related_name="question_options")
    question_answer = models.ForeignKey(
        "Option", on_delete=models.CASCADE, blank=True, null=True
    )
    group = models.ForeignKey("QuestionGroup", on_delete=models.CASCADE)

    def __str__(self):
        return self.question


class Option(models.Model):
    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name


class Answer(models.Model):
    student = models.ForeignKey("Student", on_delete=models.CASCADE)  # student
    question = models.ForeignKey("Question", on_delete=models.CASCADE)  # question
    answer = models.ForeignKey("Option", on_delete=models.CASCADE)  # option

    class Meta:
        unique_together = ("student", "question")

    def __str__(self):
        return self.student.full_name


class StudentGroup(models.Model):
    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name


class Student(UUIDMixin):
    full_name = models.CharField(max_length=254)
    username = models.CharField(max_length=254, unique=True)
    group = models.ForeignKey("StudentGroup", on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name


class Exam(UUIDMixin, TimestampMixin):
    title = models.CharField(max_length=254)
    is_page = models.BooleanField(default=False)
    shuffle = models.BooleanField(default=False)
    question_group = models.ForeignKey("QuestionGroup", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=20)
    is_public = models.BooleanField(default=False)
    schedule = models.DateTimeField()
    duration = models.IntegerField(default=60) # in minutes

    def __str__(self):
        return self.title


class ExamAttempt(UUIDMixin, TimestampMixin):
    student = models.ForeignKey("Student", on_delete=models.CASCADE)
    exam = models.ForeignKey("Exam", on_delete=models.CASCADE)
    questions = models.ManyToManyField("Question")
    score = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.student} attempted {self.exam} at {self.created_at}"

    class Meta:
        ordering = ("-created_at",)


class Device(UUIDMixin, TimestampMixin):
    name = models.CharField(max_length=254)
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return self.name


class DeviceSession(UUIDMixin, TimestampMixin):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, blank=True, null=True
    )
    device = models.ForeignKey("Device", on_delete=models.CASCADE)
    device_info = models.JSONField(null=True, blank=True)
    session_key = models.CharField(max_length=254)

    def __str__(self) -> str:
        return "Session of " + self.device.name

    class Meta:
        ordering = ("-created_at",)

exam/views.py
import random
import json
from datetime import datetime

from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth import logout
from django.utils import timezone

from main.models import Exam, Student, ExamAttempt, Question, Option, Answer


# Create your views here.


def index_view(request):
    if request.user.is_authenticated:
        exams = Exam.objects.filter(is_public=True)
        return render(request, "exam/exam_index.html", {"exams": exams})
    else:
        return HttpResponseForbidden()


def exam_overview_view(request, exam_id):
    exam = Exam.objects.get(id=exam_id)
    return render(request, "exam/exam_overview.html", {"exam": exam})


def exam_join_view(request, exam_id):
    exam = Exam.objects.get(id=exam_id)
    current_time = timezone.now()  # Get the current time in UTC
    print(current_time)
    if current_time <= exam.schedule:
        return redirect("exam:exam_overview", exam_id=exam_id)

    if request.method == "POST":
        data = request.POST
        username = data.get("username")
        try:
            student = Student.objects.get(username=username)
            student_attempts = ExamAttempt.objects.filter(student=student, exam=exam)
            if student_attempts.exists():
                messages.error(request, "You have already passed this exam")
                return redirect("exam:exam_join", exam_id=exam_id)
            request.session["current_user_username"] = student.username
            question_group = exam.question_group
            question_group_questions = list(question_group.question_set.all())
            random_questions = random.sample(question_group_questions, exam.quantity)
            exam_attempt = ExamAttempt(exam=exam, student=student)
            exam_attempt.save()
            for question in random_questions:
                exam_attempt.questions.add(question)
            return redirect("exam:exam_view", exam_id=exam_id)
        except Student.DoesNotExist:
            messages.error(request, "student does not exist with this username")
            return redirect("exam:exam_join", exam_id=exam_id)

    return render(request, "exam/exam_join.html", {"exam": exam})


def exam_view(request, exam_id):
    try:
        exam = Exam.objects.get(id=exam_id)
    except Exam.DoesNotExist:
        return Http404()
    
    student_username = request.session["current_user_username"]
    student = Student.objects.get(username=student_username)
    student_exam = student.examattempt_set.first()
    if request.method == "POST":
        student_exam.submitted = True
        student_exam.save()
        return redirect(
            "exam:results",
            exam_id=student_exam.exam.id,
            attempt_id=student_exam.id
        )
    return render(
        request, "exam/exam.html", {"exam": exam, "student_exam": student_exam}
    )


def check_answer_view(request, exam_id, attempt_id):
    if request.method == "POST":
        data = json.loads(request.body)
        question_id = str(data.get("question_id"))
        option_id = int(data.get("option_id"))
        student_username = request.session["current_user_username"]
        student = Student.objects.get(username=student_username)
        exam_attempt= ExamAttempt.objects.get(id=attempt_id)
        question = Question.objects.get(id=question_id)
        option = Option.objects.get(id=option_id)
        if Answer.objects.filter(student=student, question=question).exists():
            return JsonResponse({"error": "student answered this question already"})
        answer = Answer.objects.create(student=student, question=question, answer=option)
        if question.question_answer.id == option_id:
            exam_attempt.score += 1
            exam_attempt.save()
            print("FOuND TRUE, ", exam_attempt.score)
            return JsonResponse({"success": True})
        else:
            return JsonResponse({"success": False})


def exam_results(request, exam_id, attempt_id):
    exam = Exam.objects.get(id=exam_id)
    attempt = ExamAttempt.objects.get(id=attempt_id)
    student_username = request.session["current_user_username"]
    student = Student.objects.get(username=student_username)
    answers = Answer.objects.filter(student=student, question__in=attempt.questions.all())
    return render(request, "exam/results.html", {"result": attempt, "answers": answers })

templates/exam/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/root.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/builtins.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/notification.css' %}" />
    {% block head %} {% endblock head %}
    <style>
      :root {
        --primary: #bb96fc;
        --secondary: #03dac5;
      }
      body {
        font-family: var(--body-font);
        background: linear-gradient(35deg, var(--primary), var(--secondary));
      }

      .exam {
        padding: 0.25rem 1rem;
        color: #fff;
        border-radius: 0.25rem;
        background: var(--first-color-light);
        font-size: 2rem;
        cursor: pointer;
      }
      .card {
        background: #fff;
        padding: 10px;
        border-radius: 5px;
        width: 100%;
        max-width: 540px;
        margin: 0 auto;
      }
      .card.correct .card-answer {
        background: green;
      }
      .card.incorrect .card-answer {
        background: red;
      }
      #results .card:not(.correct, .incorrect) {
        opacity: 0.7;
        position: relative;
      }
      #results .card.correct .question--answer {
        opacity: 0.3;
        font-size: 14px;
      }
      #results .card:not(.correct, .incorrect)::after {
        content: "";
        width: 33px;
        height: 2px;
        background-color: rgba(0, 0, 0, 0.5);
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        font-size: 33px;
      }
    </style>
    <title>{% block title%} {% endblock title %}</title>
  </head>
  <body style="max-width: 1200px; margin: 0 auto">
    {% for message in messages %} {% include "../components/notification.html"
    with message=message %} {% endfor %}
    <div class="flexed p-10 x-end position-fixed">
      <nav class="px-1">
        {% if request.user.is_staff %}
        <h3 class="mb-0">{{ request.user.username }}</h3>
        <a
          href="{% url 'main:index' %}"
          class="fs-medium"
          style="color: var(--card-focus-ring-color)"
          >go to dashboard</a
        >
        {% else %}
        <h3>{{ request.user.devicesession_set.first.device.name }}</h3>
        {% endif %}
      </nav>
    </div>

    {% block content %}{% endblock content %}

    <script>
      var notifications = document.querySelectorAll(".notification");
      notifications.forEach((notification) => {
        notification.style.display = "block";
        notification.style.transform = "translateY(0)";
      });
      function closeNotification(closeButton) {
        const notification =
          closeButton.parentElement.parentElement.parentElement;
        notification.style.transform = "translateY(-200%)";
        setTimeout(function () {
          notification.style.display = "none";
        }, 300);
      }
    </script>
  </body>
</html>

templates/exam/exam.html
{% extends './base.html' %} {% load static %} {% block title %} Exam {% endblock title %} {% block head %}
<link rel="stylesheet" href="{% static 'assets/css/exam.css' %}" />

<script defer src="{% static 'assets/js/splide.min.js' %}"></script>

<link href="{% static 'assets/css/splide.min.css' %}" rel="stylesheet" />

{% endblock head %} {% block content %}

<div class="container vh-100 flexed column">
  <div class="countdown-container" style="position: fixed; right: 20px; top: 20px; padding: 20px; border-radius: .5rem; background-color: #151515; color: #fff; font-weight: bold" id="countDownDisplay">...</div>
  <div class="row">
    <form action="" method="post" id="examForm">
      {% csrf_token %}
      <div class="col" style="display: flex; flex-direction: column; gap: 10px">
        <div style="display: flex; align-items: center; gap: 5px">
          <h2 class="m-0">{{ student_exam.student.full_name }}</h2>
          -
          <h4 class="marked m-0">{{ exam.title }}</h4>
        </div>
        {% if exam.is_page %} {% for question in student_exam.questions.all %}
        <div class="card">
          <div
            style="
              display: flex;
              flex-direction: column;
              justify-content: start;
            "
          >
            <img
              src="{% if question.image %} {{ question.image.url }} {% endif %}"
              width="200"
            />
            <span class="title"
              >{{forloop.counter}}. {{ question.question }}</span
            >
          </div>
          <div class="options">
            {% for option in question.options.all %}
            <label for="option{{ question.id }}__{{ option.id }}">
              <div class="option">
                <input
                  class="question__option"
                  type="radio"
                  name="answer{{ question.id }}"
                  id="option{{ question.id }}__{{ option.id }}"
                  value="{{ option.id }}"
                  data-question-id="{{ question.id }}"
                />
                <span>{{ option.name }}</span>
              </div>
            </label>
            {% endfor %}
          </div>
          {% if forloop.last %}
          <button type="submit" class="btn">Tugatish</button>
          {% endif %}
        </div>
        {% endfor %} {% else %}
        <section
          class="splide"
          aria-label="Splide Basic HTML Example"
          id="examSplide"
        >
          <div class="splide__track">
            <ul class="splide__list">
              {% for question in student_exam.questions.all %}
              <li class="splide__slide">
                <div class="card">
                  <div
                    style="
                      display: flex;
                      flex-direction: column;
                      justify-content: start;
                    "
                  >
                    <img
                      src="{% if question.image %} {{ question.image.url }} {% endif %}"
                      width="200"
                    />
                    <span class="title"
                      >{{forloop.counter}}. {{ question.question }}</span
                    >
                  </div>
                  <div class="options">
                    {% for option in question.options.all %}
                    <label for="option{{ question.id }}__{{ option.id }}">
                      <div class="option">
                        <input
                          class="question__option"
                          type="radio"
                          name="answer{{ question.id }}"
                          id="option{{ question.id }}__{{ option.id }}"
                          value="{{ option.id }}"
                          data-question-id="{{ question.id }}"
                        />
                        <span>{{ option.name }}</span>
                      </div>
                    </label>
                    {% endfor %}
                  </div>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
        </section>
        <div class="navigators flexed x-space-between">
          <button class="btn" id="prev" type="button">previous</button>
          <button class="btn" id="next" type="button">next</button>
        </div>
        {% endif %}
        <hr />
      </div>
    </form>
  </div>
</div>

<script>
  const csrf_token = document.querySelector(
    '[name="csrfmiddlewaretoken"]'
  ).value;
  window.addEventListener("DOMContentLoaded", () => {
    const examForm = document.getElementById("examForm")
    function startCountdown(minutes) {
      let initialTime = localStorage.getItem("countdownTime");

      if (!initialTime) {
        initialTime = minutes * 60; 
        localStorage.setItem("countdownTime", initialTime);
      }
      const countdownDisplay = document.getElementById("countDownDisplay"); 
      const countdownInterval = setInterval(() => {
        if (initialTime <= 0) {
          clearInterval(countdownInterval);
          localStorage.removeItem("countdownTime");
          countdownDisplay.innerText = "Countdown completed!";
          examForm.submit()
        } else {
          const hoursRemaining = Math.floor(initialTime / 3600);
          const minutesRemaining = Math.floor((initialTime % 3600) / 60);
          const secondsRemaining = initialTime % 60;
          
          const formattedTime = `${hoursRemaining > 0 ? hoursRemaining + ':' : ''}${minutesRemaining}:${secondsRemaining < 10 ? '0' : ''}${secondsRemaining}`;
          
          countdownDisplay.innerText = `${formattedTime}`;
          initialTime--;
          localStorage.setItem("countdownTime", initialTime);
        }
      }, 1000);
    }
    startCountdown(2)
    //startCountdown(+`{{ exam.duration }}`)
    const prevBtn = document.getElementById("prev");
    const nextBtn = document.getElementById("next");
    const options = document.querySelectorAll(".question__option");
    options.forEach((option) => {
      option.onchange = (e) => {
        const questionId = option.dataset.questionId;
        const optionId = option.value;
        const data = JSON.stringify({
          question_id: questionId,
          option_id: optionId,
        });
        fetch(`{% url 'exam:check_answer' exam.id student_exam.id %}`, {
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": csrf_token,
          },
          method: "post",
          body: data,
        })
          .then((r) => r.json())
          .then((res) => {
            const parent = option.parentElement;
            parent.parentElement.parentElement
              .querySelectorAll(".question__option")
              .forEach((o) => (o.disabled = true));
            if (res.success) {
              parent.style.borderColor = "green";
              parent.style.backgroundColor = "rgba(0, 255, 0, .1)";
            } else {
              parent.style.borderColor = "red";
              parent.style.backgroundColor = "rgba(255, 0, 0, .1)";
            }
          });
      };
    });

    const examSplide = new Splide("#examSplide", {
      arrows: false,
      pagination: false,
      drag: false,
    }).mount();

    examSplide.on("moved", function (newIndex, prevIndex, destIndex) {
      if (examSplide.length - 1 === examSplide.index) {
        nextBtn.type = "submit";
        nextBtn.innerText = "Finish";
        nextBtn.onclick = null;
      } else {
        nextBtn.type = "button";
        next.innerText = "next";
        nextBtn.onclick = () => splideGo(">");
      }
    });

    prevBtn.onclick = () => splideGo("<");
    nextBtn.onclick = () => splideGo(">");
    const splideGo = (way) => {
      examSplide.go(way);
    };
  });
</script>
{% endblock content %}

templates/exam/exam_index.html
{% extends './base.html' %} {% block title %} {% endblock %} {% block content %}

<div class="container vh-100 flexed xy-centered">
  <div style="width: 250px; height: 60vh; background-color: #dcdcdc"></div>
  <div class="card">
    <p class="fs-mid fw-bold m-few">Available exams</p>
    <div class="exams flexed column gap-1">
      {% for exam in exams %}
      <a href="{% url 'exam:exam_overview' exam.id %}" class="text">
        <div class="exam">{{ exam.title }}</div>
      </a>
      {% endfor %}
    </div>
  </div>
  <div style="width: 250px; height: 60vh; background-color: #dcdcdc"></div>
</div>
{% endblock content %}

templates/exam/exam_join.html
{% extends './base.html'%} {% block title %} Join exam {{ exam.title }} {% endblock%} {% block content %}
<style>
  button.styled {
    padding: 0.4em 0.8em;
    color: #fff;
    font-weight: bold;
    background: #26aa36;
    border: none;
    border-bottom-width: medium;
    border-bottom-style: none;
    border-bottom-color: currentcolor;
    border-radius: 2em;
    border-bottom: 2px solid rgba(0, 0, 0, 0.15);
    box-shadow: 0 0 0.2em 0 rgba(0, 0, 0, 0.1), 0 2px 0 0 rgba(0, 0, 0, 0.1);
    user-select: none;
    cursor: pointer;
    outline: none;
  }
  .box::before {
    pointer-events: none;
    content: " ";
    position: absolute;
    z-index: 1;
    top: 0.2em;
    left: 0.2em;
    right: 0.2em;
    bottom: 0.2em;
    border: 2px dashed rgba(0, 0, 0, 0.1);
  }
  .box {
    position: relative;
    padding: 1em;
    background: #eee;
    border: 1px solid #ccc;
    box-shadow: 0 0 1em rgba(0, 0, 0, 0.05), 0 0.2em 0.3em rgba(0, 0, 0, 0.05),
      0 0 0.2em inset rgba(255, 255, 255, 0.5);
    border-radius: 0.25em;
  }
  .setNickname.page .line {
    margin-top: 0.5em;
  }
  .setNickname.page .nickname {
    margin-right: 0.5em;
  }
  input.styled {
    box-shadow: 0 2px rgba(32, 32, 32, 0.05) inset;
  }
  input.styled,
  input.styled:disabled,
  textarea.styled,
  select.styled {
    padding: 0.4em;
    border-radius: 0.2em;
    background: #fff;
    border: 1px solid #bbb;
    color: #222;
  }
</style>
<div class="vh-100 flexed xy-centered">
  <div style="transform: scale(1.5)">
    <form class="setNickname box" method="post" action="">
      {% csrf_token %}
      <div data-text="enterYourNickname">Enter your username:</div>
      <div class="flexed y-centered gap-few">
        <input
          class="styled nickname"
          type="text"
          placeholder="Your username"
          data-placeholder-text="yourName"
          required=""
          minlength="2"
          maxlength="64"
          autocomplete="off"
          autocorrect="off"
          autocapitalize="none"
          spellcheck="false"
          name="username"
        />
        <button class="styled">OK</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/exam/exam_overview.html
{% extends './base.html' %} {% block title %} {{ exam.title }} overview {% endblock %} {% block content %}
<style>
  .timer::before {
    content: "exam is scheduled, u can start it after";
    position: absolute;
    opacity: 0.5;
    top: -5px;
  }
</style>

<div class="container vh-100 flexed xy-centered">
  <div>
    <div class="timer position-relative">
      <span style="font-size: 4vw" id="countdown"></span>
    </div>
  </div>
</div>

<script>
  console.log("{{ exam.schedule|date:'Y-m-d H:i:s' }}");
  const examScheduleTimestamp = new Date(
    "{{ exam.schedule|date:'Y-m-d H:i:s' }}"
  ).getTime();
  const currentTime = new Date().getTime();
  const timeDifference = examScheduleTimestamp - currentTime;
  const days = Math.floor(timeDifference / (1000 * 60 * 60 * 24));
  const hours = Math.floor(
    (timeDifference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
  );
  const minutes = Math.floor((timeDifference % (1000 * 60 * 60)) / (1000 * 60));
  const seconds = Math.floor((timeDifference % (1000 * 60)) / 1000);
  function startCountdown(days, hours, minutes, seconds) {
    const countdownElement = document.getElementById("countdown");
    countdownElement.innerHTML = `${days}:${hours}:${minutes}:${seconds}s`;

    // Calculate the target time in milliseconds
    const targetTime =
      new Date().getTime() +
      days * 86400000 +
      hours * 3600000 +
      minutes * 60000 +
      seconds * 1000;

    // Update the countdown every second
    const countdownInterval = setInterval(function () {
      const currentTime = new Date().getTime();
      const timeLeft = targetTime - currentTime;

      if (timeLeft <= 0) {
        clearInterval(countdownInterval);
        countdownElement.innerHTML = "Countdown expired!";
        window.location.pathname = "{% url 'exam:exam_join'  exam.id %}"
      } else {
        const daysLeft = Math.floor(timeLeft / 86400000);
        const hoursLeft = Math.floor((timeLeft % 86400000) / 3600000);
        const minutesLeft = Math.floor((timeLeft % 3600000) / 60000);
        const secondsLeft = Math.floor((timeLeft % 60000) / 1000);

        countdownElement.innerHTML = `${daysLeft}:${hoursLeft}:${minutesLeft}:${secondsLeft}s`;
      }
      // Example usage: start countdown with 2 days, 4 hours, 30 minutes, and 15 seconds
    }, 1000);
  }
  startCountdown(days, hours, minutes, seconds);
</script>
{% endblock content %}

templates/exam/results.html
{% extends './base.html' %} {% block title %} Results {% endblock title%} {% block content %}

<div class="container flexed x-centered column" style="padding: 10vh 0 5vh 0; overflow: auto" id="results">
  <div class="row">
    <div class="col" style="display: flex; flex-direction: column; gap: 10px">
      <div class="flexed xy-centered gap-few">
        <h2 class="m-0">{{ result.student.full_name }}</h2>
        -
        <h4 class="marked m-0">{{ result.exam.title }}</h4>
      </div>
      <div class="flexed xy-centered gap-few">
        <h4 class="m-0">Umumiy natijangiz {{ result.score }}</h4>
      </div>
      {% for question in result.questions.all %}
      <div class="card {% for answer in question.answer_set.all %}{% if answer.student == result.student %}{% if  answer.answer == answer.question.question_answer %}correct{% else %}incorrect{% endif %}{% endif %}{% endfor %}">
        <div
          style="display: flex; gap: 10px;"
        class="y-centered">
          <span class="fw-bold title"
            >{{forloop.counter}}. {{ question.question }}</span
          >
          <span class="card-answer" style="color: #fff; border-radius: 5px; padding: .25rem; display: inline-block;">{% for answer in question.answer_set.all %} {% if answer.student == result.student %} {{answer.answer}} {%endif%} {% endfor %}</span>
        </div>
        <span class="question--answer">Answer: {{ question.question_answer.name }}</span>
        {% if forloop.last %}
        <div class="mt-1">
          <a  href="/">Navigate home</a>
        </div>
      {% endif  %}
      </div>
    
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}