exam/urls.py
from django.urls import path
from exam.views import (
    index_view,
    exam_overview_view,
    exam_join_view,
    exam_view,
    check_answer_view,
    exam_results
)

app_name = "exam"

urlpatterns = [
    path("", index_view, name="index"),
    path("exams/<uuid:exam_id>/", exam_overview_view, name="exam_overview"),
    path("exams/<uuid:exam_id>/join/", exam_join_view, name="exam_join"),
    path("exam/<uuid:exam_id>/", exam_view, name="exam_view"),
    path(
        "exam/<uuid:exam_id>/<uuid:attempt_id>/", check_answer_view, name="check_answer"
    ),
    path("exam/<uuid:exam_id>/<uuid:attempt_id>/results/", exam_results, name="results")
]

main/urls.py
from django.shortcuts import redirect
from django.urls import path
from main.views import (
    dashboard_view,
    student_groups_view,
    exams_view,
    question_groups_view,
    student_group_view,
    student_view,
    question_group_view,
    question_view,
    question_add,
    exam_view,
    devices_view,
    device_view,
    device_login_view,
)


app_name = "main"

urlpatterns = [
    path("", lambda request: redirect("main:student_groups"), name="index"),
    path("students/", student_groups_view, name="student_groups"),
    path("students/<int:student_group_id>/", student_group_view, name="student_group"),
    path(
        "students/<int:student_group_id>/<uuid:student_id>/",
        student_view,
        name="student",
    ),
    path("exams/", exams_view, name="exams"),
    path("exams/<uuid:exam_id>/", exam_view, name="exam"),
    path("questions/", question_groups_view, name="question_groups"),
    path(
        "questions/<int:question_group_id>", question_group_view, name="question_group"
    ),
    path("questions/<int:question_group_id>/add", question_add, name="question_add"),
    path(
        "questions/<int:question_group_id>/<uuid:question_id>/",
        question_view,
        name="question",
    ),
    path("devices/", devices_view, name="devices"),
    path("devices/<uuid:device_id>/", device_view, name="device"),
    path(
        "devices/<uuid:device_id>/auth/login/", device_login_view, name="device_login"
    ),
]

quizzyy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("exam.urls", namespace="exam")),
    path("dashboard/", include("main.urls", namespace="main")),
    path("__debug__", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/models.py
from django.db import models

# Create your models here.

exam/views.py
import random
import json
from datetime import datetime

from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth import logout
from django.utils import timezone

from main.models import Exam, Student, ExamAttempt, Question, Option, Answer


# Create your views here.


def index_view(request):
    if request.user.is_authenticated:
        exams = Exam.objects.filter(is_public=True)
        return render(request, "exam/exam_index.html", {"exams": exams})
    else:
        return HttpResponseForbidden()


def exam_overview_view(request, exam_id):
    exam = Exam.objects.get(id=exam_id)
    return render(request, "exam/exam_overview.html", {"exam": exam})


def exam_join_view(request, exam_id):
    exam = Exam.objects.get(id=exam_id)
    current_time = timezone.now()  # Get the current time in UTC
    print(current_time)
    if current_time <= exam.schedule:
        return redirect("exam:exam_overview", exam_id=exam_id)

    if request.method == "POST":
        data = request.POST
        username = data.get("username")
        try:
            student = Student.objects.get(username=username)
            student_attempts = ExamAttempt.objects.filter(student=student, exam=exam)
            if student_attempts.exists():
                messages.error(request, "You have already passed this exam")
                return redirect("exam:exam_join", exam_id=exam_id)
            request.session["current_user_username"] = student.username
            question_group = exam.question_group
            question_group_questions = list(question_group.question_set.all())
            random_questions = random.sample(question_group_questions, exam.quantity)
            exam_attempt = ExamAttempt(exam=exam, student=student)
            exam_attempt.save()
            for question in random_questions:
                exam_attempt.questions.add(question)
            return redirect("exam:exam_view", exam_id=exam_id)
        except Student.DoesNotExist:
            messages.error(request, "student does not exist with this username")
            return redirect("exam:exam_join", exam_id=exam_id)

    return render(request, "exam/exam_join.html", {"exam": exam})


def exam_view(request, exam_id):
    try:
        exam = Exam.objects.get(id=exam_id)
    except Exam.DoesNotExist:
        return Http404()
    
    student_username = request.session["current_user_username"]
    student = Student.objects.get(username=student_username)
    student_exam = student.examattempt_set.first()
    if request.method == "POST":
        student_exam.submitted = True
        student_exam.save()
        return redirect(
            "exam:results",
            exam_id=student_exam.exam.id,
            attempt_id=student_exam.id
        )
    return render(
        request, "exam/exam.html", {"exam": exam, "student_exam": student_exam}
    )


def check_answer_view(request, exam_id, attempt_id):
    if request.method == "POST":
        data = json.loads(request.body)
        question_id = str(data.get("question_id"))
        option_id = int(data.get("option_id"))
        student_username = request.session["current_user_username"]
        student = Student.objects.get(username=student_username)
        exam_attempt= ExamAttempt.objects.get(id=attempt_id)
        question = Question.objects.get(id=question_id)
        option = Option.objects.get(id=option_id)
        if Answer.objects.filter(student=student, question=question).exists():
            return JsonResponse({"error": "student answered this question already"})
        answer = Answer.objects.create(student=student, question=question, answer=option)
        if question.question_answer.id == option_id:
            exam_attempt.score += 1
            exam_attempt.save()
            print("FOuND TRUE, ", exam_attempt.score)
            return JsonResponse({"success": True})
        else:
            return JsonResponse({"success": False})


def exam_results(request, exam_id, attempt_id):
    exam = Exam.objects.get(id=exam_id)
    attempt = ExamAttempt.objects.get(id=attempt_id)
    student_username = request.session["current_user_username"]
    student = Student.objects.get(username=student_username)
    answers = Answer.objects.filter(student=student, question__in=attempt.questions.all())
    return render(request, "exam/results.html", {"result": attempt, "answers": answers })

templates/base.html
{% load static %}
{% load nav_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
    />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <script defer src="{% static 'assets/js/index.js' %}"></script>
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body id="body-pd">
    <header class="header" id="header">
      <div class="header_toggle">
        <i class="bx bx-menu" id="header-toggle"></i>
      </div>
      <div class="header_img">
        <img src="https://i.imgur.com/hczKIze.jpg" alt="" />
      </div>
    </header>
    <div class="l-navbar" id="nav-bar">
      <nav class="nav">
        <div>
          <a href="{% url 'main:index' %}" class="nav_logo">
            <i class="bx bx-layer nav_logo-icon"></i>
            <span class="nav_logo-name">Quizzy</span>
          </a>
          <div class="nav_list">
            <a href="{% url 'main:student_groups' %}" class="nav_link {% active_link request 'main:student_groups' %}">
              <i class="bx bx-user nav_icon"></i>
              <span class="nav_name">Students</span>
            </a>
            <a href="{% url 'main:exams' %}" class="nav_link {% active_link request 'main:exams' %}">
              <i class="bx bx-message-square-detail nav_icon"></i>
              <span class="nav_name">Exams</span>
            </a>
            <a href="{% url 'main:question_groups' %}" class="nav_link {% active_link request 'main:question_groups' %}">
              <i class="bx bx-folder nav_icon"></i>
              <span class="nav_name">Questions</span>
            </a>
            <a href="{% url 'main:devices' %}" class="nav_link {% active_link request 'main:devices' %}">
              <i class="bx bx-devices nav_icon"></i>
              <span class="nav_name">Devices</span>
            </a>
          </div>
        </div>
        <a href="{% url 'admin:logout' %}" class="nav_link">
          <i class="bx bx-log-out nav_icon"></i>
          <span class="nav_name">SignOut</span>
        </a>
      </nav>
    </div>

    {% block content %}
     {% endblock content %}

    <script>
      function showModal({ name }) {
        const modal = document.getElementById(name);
        modal.classList.remove("hide");
      }
      function closeModal({ name }) {
        const modal = document.getElementById(name);
        modal.classList.add("hide");
      }
    </script>
    {% block script %} {% endblock script %}
  </body>
</html>

templates/device.html
{% extends './base.html' %} {% block title %} Question Groups {% endblock title %}   {% block content %}
<!--Container Main start-->
{% url 'main:devices' as devices_url %}
{% url 'main:device_login' device.id as device_login_url %}
{% include './components/addObjectModal.html' with name="new device" modal_id="addNewDeviceModal" modal_title="Create device" post=devices_url  %}
{% include './components/addSessionModal.html' with modal_id="addNewSessionModal" modal_title="New Session"%}

<div
  class="height-100"
  style="background-color: var(--white-color); display: flex; gap: 20px"
>
  <div class="panel" style="max-width: 33%">
    <!-- <div class="title">
          <h1>Question Groups</h1>
        </div> -->

    <div
      class="content"
      style="display: flex; flex-direction: column; gap: 10px"
    >
      <div
        style="
          display: flex;
          justify-content: space-between;
          align-items: center;
        "
      >
        <h4>Devices</h4>
        <div>
          <i class="bx bx-sm bx-edit" onclick="showModal({ name: 'addNewDeviceModal'})"></i>
        </div>
      </div>
      <div
        class="panel-cards"
        style="
          display: flex;
          flex-direction: column;
          gap: 10px;
          margin-top: 18px;
        "
      >
        {% for device in devices %}
        <a href="{% url 'main:device' device.id %}">
          <div class="panel-card">
            <div class="content">
              <div>
                <h4>{{ device.name }}</h4>
                <p>
                  <span style="color: lime"
                    >{{  device.created_at }}</span
                  >
                  <span style="color: red">{{ device.devicesession_set.all|length }} sessions</span>
                </p>
              </div>
              <div>
                <i class="bx bx-md bx-chevron-right"></i>
              </div>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="panel" style="max-width: 33%">
    <!-- <div class="title">
          <h1>Question Groups</h1>
        </div> -->

    <div
      class="content"
      style="display: flex; flex-direction: column; gap: 10px"
    >
      <div
        style="
          display: flex;
          justify-content: space-between;
          align-items: center;
        "
      >
        <h4>Sessions</h4>
        <div>
          <i class="bx bx-sm bx-edit" onclick="showModal({ name: 'addNewSessionModal'})"></i>
        </div>
      </div>
      <div
        class="panel-cards"
        style="
          display: flex;
          flex-direction: column;
          gap: 10px;
          margin-top: 18px;
        "
      >
        {% for device_session in device.devicesession_set.all %}
          <div class="panel-card">
            <div class="content">
              <div>
                <h4>{{ device_session.device_info|parse:"browser" }}</h4>
                <p>
                  <span style="color: lime"
                    >{{ device.created_at }}</span
                  >
                  <span style="color: red">{{ device_session.device_info|parse:"device"}}, {{ device_session.device_info|parse:"os"}}</span>
                  <span style="color: lime;">{{ device_session.device_info|parse:"ip_addr"}}</span>
                </p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<!--Container Main end-->
{% endblock content %}

templates/devices.html
{% extends './base.html' %} {% block title %} Question Groups {% endblock title %}   {% block content %}
<!--Container Main start-->
{% url 'main:devices' as devices_url %}
{% include './components/addObjectModal.html' with name="new device" modal_id="addNewDeviceModal" modal_title="Create device" post=devices_url  %}

<div
  class="height-100"
  style="background-color: var(--white-color); display: flex; gap: 20px"
>
  <div class="panel" style="max-width: 33%">
    <!-- <div class="title">
          <h1>Question Groups</h1>
        </div> -->

    <div
      class="content"
      style="display: flex; flex-direction: column; gap: 10px"
    >
      <div
        style="
          display: flex;
          justify-content: space-between;
          align-items: center;
        "
      >
        <h4>Devices</h4>
        <div>
          <i class="bx bx-sm bx-edit" onclick="showModal({ name: 'addNewDeviceModal'})"></i>
        </div>
      </div>
      <div
        class="panel-cards"
        style="
          display: flex;
          flex-direction: column;
          gap: 10px;
          margin-top: 18px;
        "
      >
        {% for device in devices %}
        <a href="{% url 'main:device' device.id %}">
          <div class="panel-card">
            <div class="content">
              <div>
                <h4>{{ device.name }}</h4>
                <p>
                  <span style="color: lime"
                    >{{ device.created_at  }}</span
                  >
                  <span style="color: red">{{ device.devicesession_set.all|length }} sessions</span>
                </p>
              </div>
              <div>
                <i class="bx bx-md bx-chevron-right"></i>
              </div>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<!--Container Main end-->
{% endblock content %}

templates/exam.html
{% extends "./base.html" %} {% block title %} Exams {% endblock title %} {% block content %}
{% url 'main:exams' as exams_url %}
{% url 'main:exam' exam.id as exam_url %}
{% include './components/examModal.html' with modal_title="Create Exam" modal_id="addExamModal" question_groups=question_groups post=exams_url %}
{% include './components/examModal.html' with post=exam_url modal_title="Update Exam" modal_id="updateExamModal" question_groups=question_groups  title=exam.title question_group=exam.question_group  quantity=exam.quantity is_page=exam.is_page shuffle=exam.shuffle is_public=exam.is_public schedule=exam.schedule|date:'Y-m-d\TH:i' duration=exam.duration %}
<!--Container Main start-->
<div
  class="height-100"
  style="background-color: var(--white-color); display: flex; gap: 20px"
>
  <div class="panel" style="max-width: 33%">
    <div
      style="display: flex; justify-content: space-between; align-items: center"
    >
      <h4>Exams</h4>
      <div>
        <i class="bx bx-sm bx-edit" onclick="showModal({ name: 'addExamModal' })"></i>
      </div>
    </div>
    {% for exam in exams %}
    <a href="{% url 'main:exam' exam.id %}">
      <div class="panel-card">
        <div class="content">
          <div>
            <h4>{{ exam.title }}</h4>
              <p >
                <span style="color: lime">{{ exam.quantity }}</span>
                <span style="color: red">questions each</span>, 
                <span>{{ exam.schedule }}</span>,
                <span style="color: lime">{% if exam.is_public %}Public{% else %}Private{% endif %}</span>
              </p>
          </div>
          <div>
            <i class="bx bx-md bx-chevron-right"></i>
          </div>
        </div>
      </div>
    </a>

    {% endfor %}
  </div>
  <div class="panel" style="max-width: 66%">
    <div
      style="
        display: flex;
        justify-content: space-between;
        align-items: center;
      "
    >
      <h4>{{ exam.title }}</h4>
      <div>
        <i
          class="bx bx-sm bx-edit"
          onclick="showModal({ name: 'updateExamModal'})"
        ></i>
      </div>
    </div>
    <div>
      <h3>Exam question set</h3>
      <div class="panel-cards">
        {% if exam.question_group %}
        <a href="{% url 'main:question_group' exam.question_group.id %}">
          <div class="panel-card">
            <div class="content">
              <div>
                <h4>
                  {{ exam.question_group.name }}
                </h4>
                <p>
                  <span style="color: lime"
                    >{{ exam.question_group.question_set.all|length }}</span
                  >
                  <span style="color: red">questions</span>
                </p>
              </div>
              <div>
                <i class="bx bx-md bx-chevron-right"></i>
              </div>
            </div></div
        ></a>
        {% endif %}
      </div>
    </div>
    <div class="mt-2">
      <h3>Exam students</h3>
      <div
        class="panel-cards"
        style="display: flex; flex-direction: column; gap: 10px"
      >
      {% for attempt in attempts %}  
        <div class="panel-card">
          <div class="content">
            <div>
              <h4>{{ attempt.student.full_name }}</h4>
              <div style="display: flex; gap: 20px">
                <span style="color: lime">{{ attempt.created_at}}</span>
                <div style="display: flex; gap: 13px">
                  <span style="color: red">{{ attempt.score }}/{{ exam.quantity }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>
<!--Container Main end-->

{% endblock content %}

templates/login_success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="refresh" content="3;url={% url 'exam:index' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/root.css' %}">
    <style>
      body {
        margin: 0;
        padding: 0;
        font-family: var(--body-font);
        background-color: var(--white-color);
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 100vh;
      }

      .container {
        text-align: center;
      }

      h1 {
        font-size: 2rem;
        margin-top: 10px;
        color: var(--first-color);
      }

      p {
        font-size: 1rem;
        color: var(--input-fg-color);
      }
    </style>
    <title>Login Success</title>
  </head>
  <body>
    <div class="container">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="80"
        height="80"
        fill="#198754"
        class="bi bi-check-circle text-success"
        viewBox="0 0 16 16"
      >
        <path
          d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zm3.97 4.97a.758.758 0 0 0-1.07 0L7 9.93 5.07 8.03a.758.758 0 0 0-1.07 0 .758.758 0 0 0 0 1.07l2.5 2.5a.758.758 0 0 0 1.07 0l5-5a.758.758 0 0 0 0-1.07z"
        />
      </svg>
      <h1 class="text-success">Login Successful</h1>
      <p>You will be redirected shortly.</p>
    </div>
  </body>
</html>

templates/question.html
{% extends './base.html' %} {% block title %} Question Groups {% endblock title %} {% block content %}

{% url 'main:question_groups' as question_groups_url %}
{% include './components/addObjectModal.html' with name="new group" modal_id="addQuestionGroupModal" modal_title="Create question group" post=question_Groups_url %}

<!--Container Main start-->
<div
  class="height-100"
  style="background-color: var(--white-color); display: flex; gap: 20px"
>
  <div class="panel" style="max-width: 33%">
    <!-- <div class="title">
          <h1>Question Groups</h1>
        </div> -->

    <div
      class="content"
      style="display: flex; flex-direction: column; gap: 10px"
    >
      <div
        style="
          display: flex;
          justify-content: space-between;
          align-items: center;
        "
      >
        <h4>Question Groups</h4>
        <div>
          <i class="bx bx-sm bx-edit" onclick="showModal({name: 'addQuestionGroupModal'})"></i>
        </div>
      </div>
      <div
        class="panel-cards"
        style="
          display: flex;
          flex-direction: column;
          gap: 10px;
          margin-top: 18px;
        "
      >
        {% for question_group in question_groups %}
        <a href="{% url 'main:question_group' question_group.id %}">
          <div class="panel-card">
            <div class="content">
              <div>
                <h4>{{ question_group.name }}</h4>
                <p>
                  <span style="color: lime"
                    >{{ question_group.question_set.all|length }}</span
                  >
                  <span style="color: red">questions</span>
                </p>
              </div>
              <div>
                <i class="bx bx-md bx-chevron-right"></i>
              </div>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="panel" style="max-width: 33%">
    <!-- <div class="title">
          <h1>Question Groups</h1>
        </div> -->

    <div
      class="content"
      style="display: flex; flex-direction: column; gap: 10px"
    >
      <div
        style="
          display: flex;
          justify-content: space-between;
          align-items: center;
        "
      >
        <h4 contenteditable>{{ question_group.name }}</h4>
        <div>
          <a href="{% url 'main:question_add' question_group.id %}">
            <i class="bx bx-sm bx-edit"></i>
          </a>
        </div>
      </div>
      <div
        class="panel-cards"
        style="
          display: flex;
          flex-direction: column;
          gap: 10px;
          margin-top: 18px;
        "
      >
        {% for question in question_group.question_set.all %}
        <a href="{% url 'main:question' question_group.id question.id %}">
          <div class="panel-card">
            <div class="content">
              <div>
                <h4>{{ question.question }}</h4>
                <p>
                  <span style="color: lime"
                    >{{ question.question_answer.name }}</span
                  >
                  {% for option in question.options.all %}
                  <span style="color: red">{{ option.name }}</span>, {% endfor %}
                </p>
              </div>
              <div>
                <i class="bx bx-md bx-chevron-right"></i>
              </div>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="panel" style="max-width: 33%">
    <!-- <div class="title">
      <h1>Question Groups</h1>
    </div> -->

    <div
      class="content"
      style="display: flex; flex-direction: column; gap: 10px"
    >
      <div
        style="
          display: flex;
          justify-content: space-between;
          align-items: center;
        "
      >
        <h4 contenteditable>Question</h4>
      </div>
      <div class="form">
        <form action="" method="post">
          {% csrf_token %}
          <div class="fields">
            <div class="field">
              <label for="title">Question</label>
              <input
                class="form-input"
                type="text"
                placeholder="question"
                value="{{ question.question }}"
                name="question"
              />
            </div>
            <div class="field">
              <label>Options</label>
              {% for option in question.options.all %}
              <div class="input-group" tabindex="{{ forloop.counter }}">
                <div class="group">
                  <input type="radio" name="answer" value="{{ forloop.counter0 }}" tabindex="{{ forloop.counter }}" {% if question.question_answer.id == option.id %} checked {%endif%}/>
                </div>
                <div class="group">
                  <input
                    type="text"
                    value="{{ option.name }}"
                    class="form-input"
                    name="option"
                  />
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <button class="mt-1 button" type="submit">Update</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!--Container Main end-->
{% endblock content %}

templates/question_group.html
{% extends './base.html' %} {% block title %} Question Groups {% endblock title %}   {% block content %}
<!--Container Main start-->
{% url 'main:question_groups' as question_groups_url %}
{% include './components/addObjectModal.html' with name="new group" modal_id="addQuestionGroupModal" modal_title="Create question group" post=question_Groups_url %}
<div
  class="height-100"
  style="background-color: var(--white-color); display: flex; gap: 20px"
>
  <div class="panel" style="max-width: 33%">
    <!-- <div class="title">
          <h1>Question Groups</h1>
        </div> -->

    <div
      class="content"
      style="display: flex; flex-direction: column; gap: 10px"
    >
      <div
        style="
          display: flex;
          justify-content: space-between;
          align-items: center;
        "
      >
        <h4>Question Groups</h4>
        <div>
          <i class="bx bx-sm bx-edit" onclick="showModal({ name: 'addQuestionGroupModal'})"></i>
        </div>
      </div>
      <div
        class="panel-cards"
        style="
          display: flex;
          flex-direction: column;
          gap: 10px;
          margin-top: 18px;
        "
      >
        {% for question_group in question_groups %}
        <a href="{% url 'main:question_group' question_group.id %}">
          <div class="panel-card">
            <div class="content">
              <div>
                <h4>{{ question_group.name }}</h4>
                <p>
                  <span style="color: lime"
                    >{{ question_group.question_set.all|length }}</span
                  >
                  <span style="color: red">questions</span>
                </p>
              </div>
              <div>
                <i class="bx bx-md bx-chevron-right"></i>
              </div>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="panel" style="max-width: 33%">
    <!-- <div class="title">
          <h1>Question Groups</h1>
        </div> -->

    <div
      class="content"
      style="display: flex; flex-direction: column; gap: 10px"
    >
      <div
        style="
          display: flex;
          justify-content: space-between;
          align-items: center;
        "
      >
        <h4 contenteditable>{{ question_group.name }}</h4>
        <div>
          <a href="{% url 'main:question_add' question_group.id %}">
            <i class="bx bx-sm bx-edit"></i>
          </a>
        </div>
      </div>
      <div
        class="panel-cards"
        style="
          display: flex;
          flex-direction: column;
          gap: 10px;
          margin-top: 18px;
        "
      >
        {% for question in question_group.question_set.all %}
        <a href="{% url 'main:question' question_group.id question.id %}">
          <div class="panel-card">
            <div class="content">
              <div>
                <h4>{{ question.question }}</h4>
                <p>
                  <span style="color: lime"
                    >{{ question.question_answer.name }}</span
                  >
                  {% for option in question.options.all %}
                  <span style="color: red">{{ option.name }}</span>,
                  {% endfor %}
                </p>
              </div>
              <div>
                <i class="bx bx-md bx-chevron-right"></i>
              </div>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<!--Container Main end-->
{% endblock content %}

templates/question_groups.html
{% extends './base.html' %} {% block title %} Question Groups {% endblock title %}   {% block content %}
<!--Container Main start-->
{% url 'main:question_groups' as question_groups_url %}
{% include './components/addObjectModal.html' with name="new group" modal_id="addQuestionGroupModal" modal_title="Create question group" post=question_Groups_url %}

<div
  class="height-100"
  style="background-color: var(--white-color); display: flex; gap: 20px"
>
  <div class="panel" style="max-width: 33%">
    <!-- <div class="title">
          <h1>Question Groups</h1>
        </div> -->

    <div
      class="content"
      style="display: flex; flex-direction: column; gap: 10px"
    >
      <div
        style="
          display: flex;
          justify-content: space-between;
          align-items: center;
        "
      >
        <h4>Question Groups</h4>
        <div>
          <i class="bx bx-sm bx-edit" onclick="showModal({ name: 'addQuestionGroupModal'})"></i>
        </div>
      </div>
      <div
        class="panel-cards"
        style="
          display: flex;
          flex-direction: column;
          gap: 10px;
          margin-top: 18px;
        "
      >
        {% for question_group in question_groups %}
        <a href="{% url 'main:question_group' question_group.id %}">
          <div class="panel-card">
            <div class="content">
              <div>
                <h4>{{ question_group.name }}</h4>
                <p>
                  <span style="color: lime"
                    >{{ question_group.question_set.all|length }}</span
                  >
                  <span style="color: red">questions</span>
                </p>
              </div>
              <div>
                <i class="bx bx-md bx-chevron-right"></i>
              </div>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<!--Container Main end-->
{% endblock content %}